global:
  scrape_interval: 15s


rule_files:
  - "/etc/prometheus/alert-rules.yml"

scrape_configs:
  - job_name: "web_app"
    metrics_path: "/metrics"
    static_configs:
      - targets:
        - "dev_web-0:5000"
        - "dev_web-1:5000"

  - job_name: "cadvisor"
    metrics_path: "/metrics"
    static_configs:
      - targets:
        - "dev_cadvisor:8080"